list: $/jack/voltage/models/socialmedia/columns.yaml
modelClass: Jack\Voltage\Models\Socialmedia
title: Socialmedias
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jack/voltage/socialmedias/update/:id'
