list: $/jack/voltage/models/category/columns.yaml
modelClass: Jack\Voltage\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jack/voltage/categories/update/:id'
